Repository openshift-service-mesh/proxy, pull requests merged in 2025-07, with the labels that each got.

#29 update envoy to latest commit
  WORKSPACE
  ossm/vendor/envoy/.bazelrc
  ossm/vendor/envoy/.github/workflows/envoy-openssl.yml
  ossm/vendor/envoy/bazel/rbe/toolchains/configs/linux/clang/config/BUILD
  ossm/vendor/envoy/bazel/rbe/toolchains/configs/linux/clang_libcxx/config/BUILD
  ossm/vendor/envoy/bazel/rbe/toolchains/configs/linux/gcc/config/BUILD
  ossm/vendor/envoy/bazel/repositories.bzl
  ossm/vendor/envoy/bazel/v8_ppc64le.patch
  ossm/vendor/envoy/bssl-compat/prefixer/prefixer.cpp
  ossm/vendor/pick_envoy/load_envoy.bzl
  ossm/vendor/v8/bazel/config/BUILD.bazel
Labels: okay to merge, size/M

#30 Update envoy-openssl and dependencies
  WORKSPACE
  ossm/vendor/envoy/CODEOWNERS
  ossm/vendor/envoy/api/BUILD
  ossm/vendor/envoy/api/envoy/extensions/filters/http/ext_proc/v3/ext_proc.proto
  ossm/vendor/envoy/api/envoy/extensions/load_balancing_policies/override_host/v3/BUILD
  ossm/vendor/envoy/api/envoy/extensions/load_balancing_policies/override_host/v3/override_host.proto
  ossm/vendor/envoy/api/versioning/BUILD
  ossm/vendor/envoy/changelogs/current.yaml
  ossm/vendor/envoy/source/extensions/extensions_build_config.bzl
  ossm/vendor/envoy/source/extensions/extensions_metadata.yaml
  ossm/vendor/envoy/source/extensions/filters/http/ext_proc/ext_proc.cc
  ossm/vendor/envoy/source/extensions/filters/http/ext_proc/ext_proc.h
  ossm/vendor/envoy/source/extensions/load_balancing_policies/override_host/BUILD
  ossm/vendor/envoy/source/extensions/load_balancing_policies/override_host/config.cc
  ossm/vendor/envoy/source/extensions/load_balancing_policies/override_host/config.h
  ossm/vendor/envoy/source/extensions/load_balancing_policies/override_host/load_balancer.cc
  ossm/vendor/envoy/source/extensions/load_balancing_policies/override_host/load_balancer.h
  ossm/vendor/envoy/source/extensions/load_balancing_policies/override_host/override_host_filter_state.h
  ossm/vendor/envoy/test/common/network/connection_impl_test.cc
  ossm/vendor/envoy/test/extensions/filters/http/ext_proc/filter_test.cc
  ossm/vendor/envoy/test/extensions/load_balancing_policies/override_host/BUILD
  ossm/vendor/envoy/test/extensions/load_balancing_policies/override_host/config_test.cc
  ossm/vendor/envoy/test/extensions/load_balancing_policies/override_host/integration_test.cc
  ossm/vendor/envoy/test/extensions/load_balancing_policies/override_host/load_balancer_test.cc
  ossm/vendor/envoy/test/extensions/load_balancing_policies/override_host/test_lb.cc
  ossm/vendor/envoy/test/extensions/load_balancing_policies/override_host/test_lb.h
  ossm/vendor/envoy/test/extensions/load_balancing_policies/override_host/test_lb.proto
  ossm/vendor/pick_envoy/load_envoy.bzl
Labels: size/XXL, okay to merge

#34 Revert "downgrade go to 1.23 (#28)"
  go.mod
  go.sum
Labels: size/XS
